# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

additional:
  - "api-*"
  - "node-*"
  - "lib-*"

files:
  # files to ignore
  - "!.env*"
  - "!.github/workflows/*"
  - "!**/package*.json"
  - "!**/template-sync.yml"
  - "!README.*"
  # files to force sync
  - "**/LICENSE"
  - ".dockerignore"
  - .github/template/push.yml: .github/workflows/push.yml
  - .github/template/pull_request.yml: .github/workflows/pull_request.yml
  - .github/template/pull_request_target.yml: .github/workflows/pull_request_target.yml
  - .github/template/dependabot.yml: .github/dependabot.yml
