# ---------------------------------------------------- #
# Note: this file originates in template-template #
# ---------------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

permissions:
  contents: write
  statuses: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}


jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-javascript.yml

  npm-audit:
    uses: ./.github/workflows/job-npm-audit.yml

  npm-test:
    uses: ./.github/workflows/job-npm-test.yml
    secrets: inherit
    with:
      name: npm-test

  template-sync:
    needs:
      - metadata

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}
    uses: ./.github/workflows/job-template-sync.yml
    secrets: inherit

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content
      - npm-audit
      - npm-test

    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-semantic-release.yml
    secrets: inherit
